# Generated by Django 3.2.3 on 2021-06-03 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='stock.stock')),
            ],
        ),
    ]
